# ── Service Account ──

resource "google_service_account" "outflex" {
  account_id   = "outflex-sa"
  display_name = "Outflex Service Account"
  project      = var.project_id

  depends_on = [google_project_service.apis]
}

resource "google_project_iam_member" "outflex_ar_reader" {
  project = var.project_id
  role    = "roles/artifactregistry.reader"
  member  = "serviceAccount:${google_service_account.outflex.email}"
}

# Firestore access for the app (entries collection)
resource "google_project_iam_member" "outflex_datastore_user" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:${google_service_account.outflex.email}"

  depends_on = [google_project_service.apis]
}

# Cloud Build pushes the image to Artifact Registry
resource "google_project_iam_member" "cloud_build_compute_builder" {
  project = var.project_id
  role    = "roles/cloudbuild.builds.builder"
  member  = "serviceAccount:${data.google_project.project.number}-compute@developer.gserviceaccount.com"

  depends_on = [google_project_service.apis]
}

resource "google_project_iam_member" "cloud_build_compute_ar_writer" {
  project = var.project_id
  role    = "roles/artifactregistry.writer"
  member  = "serviceAccount:${data.google_project.project.number}-compute@developer.gserviceaccount.com"

  depends_on = [google_project_service.apis]
}

# ── Artifact Registry ──

resource "google_artifact_registry_repository" "outflex" {
  project       = var.project_id
  location      = var.region
  repository_id = "outflex-repo"
  format        = "DOCKER"
  description   = "Outflex Docker images"

  depends_on = [google_project_service.apis]
}

# ── Secrets ──

resource "google_secret_manager_secret" "stripe_secret_key" {
  secret_id = "outflex-stripe-secret-key"
  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "stripe_secret_key" {
  secret      = google_secret_manager_secret.stripe_secret_key.id
  secret_data = var.stripe_secret_key
}

resource "google_secret_manager_secret_iam_member" "stripe_secret_key_access" {
  secret_id = google_secret_manager_secret.stripe_secret_key.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.outflex.email}"
}

# The webhook signing secret is generated BY Stripe when the endpoint is
# created (stripe.tf) — Terraform stores it into Secret Manager.
resource "google_secret_manager_secret" "stripe_webhook_secret" {
  secret_id = "outflex-stripe-webhook-secret"
  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "stripe_webhook_secret" {
  secret      = google_secret_manager_secret.stripe_webhook_secret.id
  secret_data = stripe_webhook_endpoint.wall.secret
}

resource "google_secret_manager_secret_iam_member" "stripe_webhook_secret_access" {
  secret_id = google_secret_manager_secret.stripe_webhook_secret.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.outflex.email}"
}

# ── Session secret (cookie "my seat") ──

resource "random_password" "auth_session_secret" {
  length  = 64
  special = false
}

resource "google_secret_manager_secret" "auth_session_secret" {
  secret_id = "outflex-auth-session-secret"
  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "auth_session_secret" {
  secret      = google_secret_manager_secret.auth_session_secret.id
  secret_data = random_password.auth_session_secret.result
}

resource "google_secret_manager_secret_iam_member" "auth_session_secret_access" {
  secret_id = google_secret_manager_secret.auth_session_secret.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.outflex.email}"
}

# ── Cloud Run Service ──

locals {
  # Single source of truth for the public origin (lettrio pattern).
  app_url = var.domain != "" ? "https://${var.domain}" : "https://outflex-${data.google_project.project.number}.${var.region}.run.app"
}

resource "google_cloud_run_v2_service" "outflex" {
  name                 = "outflex"
  location             = var.region
  ingress              = "INGRESS_TRAFFIC_ALL"
  invoker_iam_disabled = true
  deletion_protection  = false

  template {
    service_account = google_service_account.outflex.email

    scaling {
      min_instance_count = 0
      max_instance_count = 3
    }

    containers {
      # Image managed by CI/CD — don't track in terraform
      image = "${var.region}-docker.pkg.dev/${var.project_id}/${google_artifact_registry_repository.outflex.repository_id}/outflex:latest"

      ports {
        container_port = 3000
      }

      resources {
        limits = {
          cpu    = "1"
          memory = "512Mi"
        }
        cpu_idle          = true
        startup_cpu_boost = true
      }

      env {
        name  = "NODE_ENV"
        value = "production"
      }

      env {
        name  = "NEXT_PUBLIC_APP_URL"
        value = local.app_url
      }

      env {
        name  = "GOOGLE_PROJECT_ID"
        value = var.project_id
      }

      env {
        name  = "MIN_ENTRY_USD"
        value = tostring(var.min_entry_usd)
      }

      dynamic "env" {
        for_each = local.email_enabled ? [1] : []
        content {
          name  = "EMAIL_IMPERSONATE"
          value = var.email_impersonate
        }
      }

      dynamic "env" {
        for_each = local.email_enabled && var.email_from != "" ? [1] : []
        content {
          name  = "EMAIL_FROM"
          value = var.email_from
        }
      }

      env {
        name = "AUTH_SESSION_SECRET"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.auth_session_secret.secret_id
            version = "latest"
          }
        }
      }

      env {
        name = "STRIPE_SECRET_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.stripe_secret_key.secret_id
            version = "latest"
          }
        }
      }

      env {
        name = "STRIPE_WEBHOOK_SECRET"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.stripe_webhook_secret.secret_id
            version = "latest"
          }
        }
      }
    }
  }
}

# ── Public access ──
# invoker_iam_disabled = true (ci-dessus) rend le service public sans allUsers —
# la ressource IAM allUsers est retirée : bloquée par la politique org
# "domain restricted sharing" de ghotatechsolutions.com.

# ── Domain mapping (optional) ──

resource "google_cloud_run_domain_mapping" "domain" {
  count    = var.enable_domain_mapping ? 1 : 0
  location = var.region
  name     = var.domain

  metadata {
    namespace = var.project_id
  }

  spec {
    route_name = google_cloud_run_v2_service.outflex.name
  }

  depends_on = [google_cloud_run_v2_service.outflex]
}

# www → même service (le CNAME www → ghs.googlehosted.com se règle chez le registrar)
resource "google_cloud_run_domain_mapping" "www" {
  count    = var.enable_domain_mapping ? 1 : 0
  location = var.region
  name     = "www.${var.domain}"

  metadata {
    namespace = var.project_id
  }

  spec {
    route_name = google_cloud_run_v2_service.outflex.name
  }

  depends_on = [google_cloud_run_v2_service.outflex]
}

output "www_dns_record" {
  value       = "CNAME www → ghs.googlehosted.com"
  description = "Enregistrement à ajouter chez le registrar pour www."
}
